# Generated by Django 4.0.5 on 2022-09-26 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendgridEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('emailable_id', models.IntegerField()),
                ('emailable_type', models.CharField(max_length=50)),
                ('recipient_email', models.CharField(max_length=255)),
                ('timestamp', models.CharField(max_length=20)),
                ('smtp_id', models.CharField(max_length=35)),
                ('sg_event_id', models.CharField(max_length=100)),
                ('sg_message_id', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=200)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='BounceSendgridEvent',
            fields=[
                ('sendgridevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='emails.sendgridevent')),
                ('event', models.CharField(default='bounce', editable=False, max_length=6)),
                ('bounce_classification', models.CharField(max_length=20)),
                ('ip', models.CharField(max_length=50)),
                ('reason', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('emails.sendgridevent',),
        ),
        migrations.CreateModel(
            name='ClickSendgridEvent',
            fields=[
                ('sendgridevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='emails.sendgridevent')),
                ('event', models.CharField(default='click', editable=False, max_length=5)),
                ('useragent', models.CharField(max_length=200)),
                ('ip', models.CharField(max_length=50)),
                ('url', models.URLField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('emails.sendgridevent',),
        ),
        migrations.CreateModel(
            name='DeferredSendgridEvent',
            fields=[
                ('sendgridevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='emails.sendgridevent')),
                ('event', models.CharField(default='deferred', editable=False, max_length=8)),
                ('ip', models.CharField(max_length=50)),
                ('response', models.CharField(max_length=100)),
                ('attempt', models.IntegerField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('emails.sendgridevent',),
        ),
        migrations.CreateModel(
            name='DeliveredSendgridEvent',
            fields=[
                ('sendgridevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='emails.sendgridevent')),
                ('event', models.CharField(default='delivered', editable=False, max_length=9)),
                ('ip', models.CharField(max_length=50)),
                ('response', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('emails.sendgridevent',),
        ),
        migrations.CreateModel(
            name='DroppedSendgridEvent',
            fields=[
                ('sendgridevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='emails.sendgridevent')),
                ('event', models.CharField(default='dropped', editable=False, max_length=7)),
                ('reason', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('emails.sendgridevent',),
        ),
        migrations.CreateModel(
            name='GroupResubscribeSendgridEvent',
            fields=[
                ('sendgridevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='emails.sendgridevent')),
                ('event', models.CharField(default='group_resubscribe', editable=False, max_length=16)),
                ('useragent', models.CharField(max_length=200)),
                ('ip', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('asm_group_id', models.IntegerField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('emails.sendgridevent',),
        ),
        migrations.CreateModel(
            name='GroupUnsubscribeSendgridEvent',
            fields=[
                ('sendgridevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='emails.sendgridevent')),
                ('event', models.CharField(default='group_unsubscribe', editable=False, max_length=16)),
                ('useragent', models.CharField(max_length=200)),
                ('ip', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('asm_group_id', models.IntegerField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('emails.sendgridevent',),
        ),
        migrations.CreateModel(
            name='OpenSendgridEvent',
            fields=[
                ('sendgridevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='emails.sendgridevent')),
                ('event', models.CharField(default='open', editable=False, max_length=4)),
                ('sg_machine_open', models.CharField(max_length=5)),
                ('useragent', models.CharField(max_length=200)),
                ('ip', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('emails.sendgridevent',),
        ),
        migrations.CreateModel(
            name='ProcessedSendgridEvent',
            fields=[
                ('sendgridevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='emails.sendgridevent')),
                ('event', models.CharField(default='processed', editable=False, max_length=9)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('emails.sendgridevent',),
        ),
        migrations.CreateModel(
            name='SpamReportSendgridEvent',
            fields=[
                ('sendgridevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='emails.sendgridevent')),
                ('event', models.CharField(default='spamreport', editable=False, max_length=10)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('emails.sendgridevent',),
        ),
        migrations.CreateModel(
            name='UnsubsribeSendgridEvent',
            fields=[
                ('sendgridevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='emails.sendgridevent')),
                ('event', models.CharField(default='unsubscribe', editable=False, max_length=11)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('emails.sendgridevent',),
        ),
    ]
