# Generated by Django 4.0.5 on 2022-09-28 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendgridEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('emailable_id', models.PositiveIntegerField()),
                ('emailable_type', models.CharField(max_length=50)),
                ('recipient_email', models.CharField(max_length=255)),
                ('timestamp', models.PositiveIntegerField()),
                ('sg_event_id', models.CharField(max_length=100)),
                ('sg_message_id', models.CharField(max_length=100)),
                ('sg_template_id', models.CharField(max_length=34, null=True)),
                ('sg_template_name', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BounceSendgridEvent',
            fields=[
                ('sendgridevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='emails.sendgridevent')),
                ('event', models.CharField(default='bounce', editable=False, max_length=6)),
                ('bounce_classification', models.CharField(max_length=20)),
                ('reason', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
            bases=('emails.sendgridevent',),
        ),
        migrations.CreateModel(
            name='DeferredSendgridEvent',
            fields=[
                ('sendgridevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='emails.sendgridevent')),
                ('event', models.CharField(default='deferred', editable=False, max_length=8)),
                ('attempt', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('emails.sendgridevent',),
        ),
        migrations.CreateModel(
            name='DeliveredSendgridEvent',
            fields=[
                ('sendgridevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='emails.sendgridevent')),
                ('event', models.CharField(default='delivered', editable=False, max_length=9)),
            ],
            options={
                'abstract': False,
            },
            bases=('emails.sendgridevent',),
        ),
        migrations.CreateModel(
            name='DroppedSendgridEvent',
            fields=[
                ('sendgridevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='emails.sendgridevent')),
                ('event', models.CharField(default='dropped', editable=False, max_length=7)),
                ('reason', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('emails.sendgridevent',),
        ),
        migrations.CreateModel(
            name='ProcessedSendgridEvent',
            fields=[
                ('sendgridevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='emails.sendgridevent')),
                ('event', models.CharField(default='processed', editable=False, max_length=9)),
            ],
            options={
                'abstract': False,
            },
            bases=('emails.sendgridevent',),
        ),
    ]
