# Generated by Django 4.0.5 on 2022-09-29 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_sendgridevent_bouncesendgridevent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bouncesendgridevent',
            name='status',
        ),
    ]
