# Generated by Django 4.0.5 on 2022-10-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0004_alter_bouncesendgridevent_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='droppedsendgridevent',
            name='reason',
            field=models.CharField(max_length=300),
        ),
    ]
