# Generated by Django 4.0.5 on 2022-07-12 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_coupon_couponable_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='type',
            field=models.CharField(choices=[('referral', 'Referral'), ('partnership', 'Partnership')], max_length=20),
        ),
    ]
