# Generated by Django 4.0.5 on 2022-07-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_alter_coupon_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('couponable_type', models.CharField(blank=True, max_length=50, null=True)),
                ('couponable_id', models.PositiveIntegerField(blank=True, null=True)),
                ('discount_type', models.CharField(choices=[('percent', 'Percent off'), ('dollars', 'Dollars off')], max_length=7)),
                ('discount_amount', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='couponable_id',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='couponable_type',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='discount_type',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='type',
        ),
        migrations.AddField(
            model_name='coupon',
            name='effects',
            field=models.ManyToManyField(to='payment.couponeffect'),
        ),
    ]
