# Generated by Django 4.0.5 on 2022-07-12 15:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_couponeffect_remove_coupon_couponable_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponeffect',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='couponeffect',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
