# Generated by Django 4.0.5 on 2022-07-18 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_couponeffect_created_at_couponeffect_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
