# Generated by Django 4.0.5 on 2022-08-05 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('payment', '0010_alter_coupon_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='couponeffect',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='couponeffect',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
    ]
