# Generated by Django 4.0.5 on 2022-08-05 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_alter_couponeffect_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeCouponEffect',
            fields=[
                ('couponeffect_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payment.couponeffect')),
                ('stripe_coupon_id', models.PositiveIntegerField(null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('payment.couponeffect',),
        ),
    ]
