# Generated by Django 4.0.5 on 2022-08-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_discount_stripediscount_stripepayment_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='original_amount',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='stripediscount',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
