# Generated by Django 4.0.5 on 2022-08-10 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0015_alter_discount_original_amount_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StripeCouponEffect',
        ),
    ]
