# Generated by Django 4.0.5 on 2022-08-10 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0016_delete_stripecouponeffect'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='couponeffect',
            options={},
        ),
        migrations.RemoveField(
            model_name='couponeffect',
            name='polymorphic_ctype',
        ),
    ]
