# Generated by Django 4.0.5 on 2022-08-12 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0017_alter_couponeffect_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='original_amount',
        ),
        migrations.RemoveField(
            model_name='stripediscount',
            name='amount',
        ),
        migrations.AddField(
            model_name='discount',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
