# Generated by Django 4.0.5 on 2022-09-16 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('payment', '0019_payment_deleted_at_payment_deleted_by_cascade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='coupon',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
    ]
