# Generated by Django 4.1.2 on 2022-10-10 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0021_referralcoupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='deleted_at',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='couponeffect',
            name='deleted_at',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='deleted_at',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
    ]
