# Generated by Django 4.0.4 on 2022-04-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_batch_deleted_at_course_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchschedule',
            name='course_day',
            field=models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=4),
        ),
    ]
