# Generated by Django 4.0.4 on 2022-04-29 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_batch_deleted_by_cascade_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batchschedule',
            old_name='course_day',
            new_name='day',
        ),
    ]
