# Generated by Django 4.0.5 on 2022-06-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_batchschedule_iso_week_day_alter_batchschedule_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='slack_channel_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
