# Generated by Django 4.0.5 on 2022-06-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_section_slack_channel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='slack_channel_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
