# Generated by Django 4.0.5 on 2022-08-31 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_batch_slack_channel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(choices=[('CODING_BASICS', 'Coding Basics'), ('CODING_BOOTCAMP', 'Coding Bootcamp')], max_length=255),
        ),
    ]
