# Generated by Django 4.0.5 on 2022-09-12 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_rename_slack_id_studentuser_slack_user_id'),
        ('staff', '0010_alter_course_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('credential', models.CharField(max_length=12, unique=True)),
                ('graduation_date', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.course')),
                ('student_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.studentuser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
