# Generated by Django 4.0.5 on 2022-09-13 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='student_user',
        ),
    ]
