# Generated by Django 4.1.2 on 2022-10-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0013_batch_price_batch_type_alter_batch_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='type',
            field=models.CharField(choices=[('part_time', 'Part-time'), ('full_time', 'Full-time')], max_length=9, null=True),
        ),
    ]
