# Generated by Django 4.1.3 on 2022-12-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0014_alter_batch_price_alter_batch_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(choices=[('CODING_BASICS', 'Coding Basics'), ('CODING_BOOTCAMP', 'Coding Bootcamp'), ('SOFTWARE_ENGINEERING_FUNDAMENTALS', 'Software Engineering Fundamentals')], max_length=255),
        ),
    ]
