# Generated by Django 4.1.4 on 2023-01-03 08:17

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0078_referenceindex'),
        ('staff', '0016_coursepage_batchpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.RichTextField(blank=True)),
                ('batch_page', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staff.batchpage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
