# Generated by Django 4.0.5 on 2022-06-10 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_studentuser_user_polymorphic_ctype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='hubspot_contact_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
