# Generated by Django 4.0.5 on 2022-06-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_studentuser_hubspot_contact_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='slack_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
