# Generated by Django 4.0.5 on 2022-06-20 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_studentuser_slack_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentuser',
            old_name='slack_id',
            new_name='slack_user_id',
        ),
    ]
