# Generated by Django 4.0.4 on 2022-05-26 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_batchschedule_iso_week_day_alter_batchschedule_day'),
        ('student', '0002_alter_registration_country_of_residence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='staff.course'),
            preserve_default=False,
        ),
    ]
