# Generated by Django 4.0.4 on 2022-06-03 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_batchschedule_iso_week_day_alter_batchschedule_day'),
        ('student', '0003_registration_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolment',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.section'),
        ),
    ]
