# Generated by Django 4.0.5 on 2022-06-16 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_studentuser_hubspot_contact_id'),
        ('student', '0004_alter_enrolment_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolment',
            name='user',
        ),
        migrations.AddField(
            model_name='enrolment',
            name='student_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.studentuser'),
        ),
    ]
