# Generated by Django 4.0.5 on 2022-07-06 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_remove_enrolment_user_enrolment_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='referral_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
