# Generated by Django 4.0.5 on 2022-07-13 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_registration_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolment',
            name='registration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.registration'),
        ),
    ]
