# Generated by Django 4.0.5 on 2022-07-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_enrolment_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='referral_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
