# Generated by Django 4.0.5 on 2022-08-31 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_alter_registration_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolment',
            name='status',
            field=models.CharField(choices=[('ENROLLED', 'Enrolled'), ('PASSED', 'Passed'), ('FAILED', 'Failed')], default='ENROLLED', max_length=15),
        ),
    ]
