# Generated by Django 4.1.3 on 2022-12-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_alter_enrolment_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolment',
            name='status',
            field=models.CharField(choices=[('ENROLLED', 'Enrolled'), ('PASSED', 'Passed'), ('FAILED', 'Failed'), ('DEFERRED', 'Deferred')], default='ENROLLED', max_length=15),
        ),
    ]
