name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  COMPRESS_OFFLINE: False
  DJANGO_ALLOWED_HOSTS: .localhost,127.0.0.1
  DJANGO_DEBUG: True
  DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
  DOMAIN_URL: http://localhost:8000
  HUBSPOT_API_KEY: ${{ secrets.HUBSPOT_API_KEY }}
  HUBSPOT_PRIVATE_APP_ACCESS_TOKEN: ${{ secrets.HUBSPOT_PRIVATE_APP_ACCESS_TOKEN }}
  POSTGRES_DB_NAME: learn
  SLACK_CODING_BASICS_WORKSPACE_INVITE_LINK: ${{ secrets.SLACK_CODING_BASICS_WORKSPACE_INVITE_LINK }}
  SLACK_USER_OAUTH_TOKEN: ${{ secrets.SLACK_USER_OAUTH_TOKEN }}
  SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
  SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
  STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_PUBLISHABLE_KEY }}
  STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
  STRIPE_ENDPOINT_SECRET: ${{ secrets.STRIPE_ENDPOINT_SECRET }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev
      - name: Run collectstatic
        run: |
          pipenv run python manage.py collectstatic
      - name: Test with pytest
        run: |
          pipenv run pytest
